name: semicon-sr
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  # Python
  - python=3.12

  # PyTorch with CUDA support
  - pytorch::pytorch>=2.1.0
  - pytorch::torchvision>=0.16.0
  - pytorch::torchaudio>=2.1.0
  - pytorch::pytorch-cuda=12.1  # Adjust version based on your CUDA

  # Scientific Computing (conda-optimized)
  - numpy>=1.24.0
  - scipy>=1.11.0
  - scikit-image>=0.22.0
  - scikit-learn>=1.3.0
  - pandas>=2.1.0

  # Image Processing
  - opencv>=4.8.0
  - pillow>=10.0.0
  - imageio>=2.31.0

  # Visualization
  - matplotlib>=3.8.0
  - seaborn>=0.13.0
  - plotly>=5.17.0

  # Development Tools
  - jupyter>=1.0.0
  - ipython>=8.15.0
  - notebook>=7.0.0

  # Configuration
  - pyyaml>=6.0.1

  # Progress and Utilities
  - tqdm>=4.66.0

  # Testing
  - pytest>=7.4.0
  - pytest-cov>=4.1.0

  # Code Quality
  - black>=23.9.0
  - flake8>=6.1.0
  - isort>=5.12.0

  # GPU Monitoring
  - gpustat>=1.1.0

  # Pip dependencies (not available or better via pip)
  - pip
  - pip:
      # Vision Transformers
      - timm>=0.9.0

      # Semiconductor-specific image formats
      - tifffile>=2023.9.0

      # Experiment Tracking
      - wandb>=0.15.0
      - tensorboard>=2.14.0
      - tensorboardX>=2.6.0

      # Perceptual Metrics
      - lpips>=0.1.4
      - pytorch-fid>=0.3.0

      # ONNX Deployment
      - onnx>=1.15.0
      - onnxruntime-gpu>=1.16.0

      # Advanced Configuration
      - hydra-core>=1.3.0
      - omegaconf>=2.3.0

      # Enhanced Logging and Output
      - rich>=13.5.0
      - colorama>=0.4.6
      - loguru>=0.7.0

      # Development
      - ipywidgets>=8.1.0
      - mypy>=1.5.0
      - pylint>=2.17.0
      - pytest-xdist>=3.3.0
      - pytest-timeout>=2.1.0

      # Documentation
      - sphinx>=7.2.0
      - sphinx-rtd-theme>=1.3.0
      - sphinx-autodoc-typehints>=1.24.0

      # Utilities
      - python-dotenv>=1.0.0
      - einops>=0.7.0
      - h5py>=3.9.0
      - pyarrow>=13.0.0
      - pynvml>=11.5.0
